[package]
name = "data-generator"
version = "0.1.0"
authors = ["stefano <s.kouroupis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.53"