[package]
name = "spawnflakes"
version = "0.2.1"
authors = ["stefano <s.kouroupis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
spawnflake = "0.2.2"
clap = "2.33.3"
